export const STOP_CAPTURE_PROMPT = [
  'If this turn taught something reusable that should change what an agent does next time, propose it; most turns warrant no proposal.',
  'Propose only lessons or decisions with a future behavioral consequence, using a proposals array; there is no count limit, and none is expected.',
  'Include trigger, behavior_delta, why, topic_key, evidence_refs and any assumptions or revision conditions, written in English whatever the conversation language.',
  'Set capture_origin to model_initiated unless the user explicitly asked to save that specific knowledge; then use user_explicit. A requested development task alone is not an explicit memory request.',
  'Use actual file references, or the ID of a recorded host observation or user correction; never invent user approval. Compact forms are generated by DD.',
  'If nothing should change next time, do not propose.',
  'Do not dump the transcript or tool logs.',
].join(' ');
