export const STOP_CAPTURE_PROMPT = [
  'Propose newly learned reusable lessons or decisions with a future behavioral consequence, using a proposals array. There is no proposal count limit per call or session.',
  'Include trigger, behavior_delta, why, topic_key, evidence_refs and any assumptions or revision conditions.',
  'Set capture_origin to model_initiated unless the user explicitly asked to save that specific knowledge; then use user_explicit. A requested development task alone is not an explicit memory request.',
  'Use actual file references, or the ID of a recorded host observation or user correction; never invent user approval. Compact forms are generated by DD.',
  'If nothing should change next time, do not propose.',
  'Do not dump the transcript or tool logs.',
].join(' ');
